---
title: "Development actions history"
output: html_document
editor_options: 
  chunk_output_type: console
---

All commands that you use to use when developing packages...

# First time just after creating the project

```{r description}
# Describe your package
fusen::fill_description(overwrite = TRUE,
  pkg = here::here(),
  fields = list(
    Title = "Data from CHOPIN research project",
    Description = "Provide well-documented, ready-to-use R data objects.",
    `Authors@R` = c(
      person("Florence", "Mounier", email = "florence.mounier42@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-8916-7007"))
    )
  )
)

# Define License with use_*_license()
usethis::use_mit_license("Florence Mounier")

# Deal with classical files to ignore
usethis::git_vaccinate()

# Install a first time
remotes::install_local()

# README
usethis::use_readme_rmd()

# Code of Conduct
usethis::use_code_of_conduct("florence.mounier42@gmail.com")

# Set Continuous Integration
# _GitHub (included in `init_share_on_github()`)
usethis::use_github_action("check-standard")
usethis::use_github_action("pkgdown")
```

**From now, you will need to "inflate" your package at least once to be able to use the following commands. Let's go to your flat template, and come back here later if/when needed.**


# Package development tools
## Use once

```{r, eval=FALSE}
# Use roxygen2
devtools::document()
# Pipe
usethis::use_pipe()

# package-level documentation
# usethis::use_package_doc()


```

## Use everytime needed

```{r, eval=FALSE}
# Simulate package installation
pkgload::load_all()

# Generate documentation and deal with dependencies
attachment::att_amend_desc()

# Check the package
devtools::check()

# Add a new flat template
fusen::add_flat_template("add")

# Inflate all flat files at once
fusen::inflate_all()

# Package structure (add this in a dev/Readme.md file)
fusen::draw_package_structure()
```

# Share the package

```{r, eval=FALSE}
# set and try pkgdown documentation website locally
usethis::use_pkgdown()
pkgdown::build_site()

# build the tar.gz with vignettes to share with others
devtools::build(vignettes = TRUE)

# Share your package and its documentation on GitHub
# usethis::create_github_token()
# gitcreds::gitcreds_set()
fusen::init_share_on_github()
```

