# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute concentrations in another unit
#' 
#' @param data tibble dataset of source concentrations
#' @param contams character vector of contaminant names
#' @param source_unit character unit of source concentrations
#' @param target_unit character unit of target concentrations
#' @param norm_var character suffix of target concentrations
#' @param operation character type of operation ("divide", "multiply")
#'
#' @return tibble completed contamination data with target concentrations
#' 
#' @import dplyr
#' 
#' @export
#' @examples
#' ## Add lipid-normalized concentrations for PCBs
#' # benthos_contam <- benthos_contam |>
#' #   convert_conc(
#' #     contams = PCB,
#' #     source_unit = "_ng_g-1ps",
#' #     target_unit = "_ng_g.1pl",
#' #     norm_var = "lip_PS_percent",
#' #     operation = "divide"
#' #   )
convert_conc <- function(data, contams, source_unit = NULL,
                         target_unit, norm_var,
                         operation = c("divide", "multiply")) {
  
  operation <- match.arg(operation)
  
  for (contam in contams) {
    
    source_col <- if (is.null(source_unit)) {
      contam
    } else {
      paste0(contam, source_unit)
    }
    
    target_col <- paste0(contam, target_unit)
    
    if (operation == "divide") {
      data[[target_col]] <- data[[source_col]] / (data[[norm_var]] / 100)
    }
    
    if (operation == "multiply") {
      data[[target_col]] <- data[[source_col]] * (data[[norm_var]] / 100)
    }
  }
  
  return(data)
}
