# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Complete data with sum by family-normalised concentrations
#' 
#' @param family character family of contaminants
#' @param contams R object vector of compounds names
#' @param data tibble dataset of concentrations
#' @param unit character unit of concentrations
#'
#' @return tibble completed contamination data
#' 
#' @export
normalised_conc <- function(family, contams, data, unit) {
  
  cols_contam <- paste(contams, unit, sep = "_")
  
  data |>
    mutate(
      across(
        all_of(cols_contam),
        ~ norm_conc_subfct(
          data = data,
          contam_unit = .x,
          family = family,
          unit = unit
        ),
        .names = "{.col}_tmp"
      )
    ) |>
    rename_with(
      .cols = ends_with("_tmp"),
      ~ sub(
        paste0("_", unit, "_tmp$"),
        paste0("_normalised_sum_", unit),
        .x
      )
    )
}
