# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute sum by family-normalised concentrations
#' 
#' @param contam_unit character concentrations unit
#' @param data tibble dataset of concentrations
#'
#' @return numeric vector of normalised concentrations
#' 
#' @noRd
norm_conc_subfct <- function(data, contam_unit, family, unit) {
  
  col_sum <- paste("sum", family, unit, sep = "_")
  
  sum_unit <- data[[col_sum]]
  
  sum_conc <- contam_unit / sum_unit
  
  return(sum_conc)
}
