# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute sum of concentrations by family
#' 
#' @param contams R object vector of compounds names
#' @param data tibble dataset of concentrations
#' @param unit character unit of concentrations
#'
#' @return numeric vector of sum of concentrations by family
#' 
#' @import dplyr
#' 
#' @noRd
sum_by_family_subfct <- function(contams, data, unit) {
  summed_data <- data |>
    select(contains(contams) & ends_with(paste(unit))) |>
    rowSums(na.rm = TRUE)
  
  return(summed_data)
}
