# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Complete data with sum of concentrations by family
#' 
#' @param family character family of contaminants
#' @param contams R object vector of compounds names
#' @param data tibble dataset of concentrations
#' @param unit character unit of concentrations
#'
#' @return tibble completed contamination data with sum of concentrations by family
#' 
#' @export
sum_by_family <- function(family, contams, data, unit) {
  completed_data <- data |>
    mutate(tmp_sum = sum_by_family_subfct(contams, data, unit)) |>
    rename_with( ~ gsub("tmp_sum", paste("sum", family, unit, sep = "_"), x = .x))
  
  return(completed_data)
}
