# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand # nolint: line_length_linter.

#' wrangle_contam Get contaminant vectors from table in CHOPIN_general_DB.xlsx
#'
#' @param grp_contam character name of contaminant group
#' @param grp_type character type of contaminant group ("family" or "sub_family_TAG")
#' @param out_var character column name of output variable
#'
#' @return character vector of contaminant names
#' 
#' @import dplyr
#' 
#' @noRd
wrangle_contam <- function(data = chopin.data::contam_info,
                           grp_contam, grp_type, out_var){
  data |> 
    filter(!!sym(grp_type) == grp_contam) |> 
    pull(!!sym(out_var))
}
